### ISSUE TITLE
Windows.Devices.SmartCards doesn't appear to be working

### ISSUE THREAD

**Issue by alexrsagen** [NodeRT/NodeRT#35]
#### Sample code

``` javascript
const smartcards = require("windows.devices.smartcards")
const sc = new smartcards.SmartCard()
const reader = new smartcards.SmartCardReader()
```
#### Error produced

```
Uncaught Error: Invalid arguments, no suitable constructor found
```
#### Versions

windows: 10.0.10240
windows 10 sdk: 10.0.14393.0
node: 6.4.0
npm: 3.10.7
electron: 1.3.5
## 

The module was not installed using npm, i generated it with NodeRTUI and built it myself. Absolutely no build errors, just two neglectible type casting warnings.

The error above occurs both when trying to use `new smartcards.SmartCard()` and `new smartcards.SmartCardReader()`.

Interestingly enough, when i call `smartcards.SmartCard()` without the `new` keyword, the renderer process crashes by illegally attempting to write to memory at location 0x00. This seems to have to do with line 942 of the generated code, which looks like this on my build:

``` c++
info.GetReturnValue().Set(Nan::CallAsConstructor(Nan::GetFunction(localRef).ToLocalChecked(), info.Length(), nullptr).ToLocalChecked());
```
## 
#### Side note

Using the module in the browser process of electron causes it to throw `error in CoInitializeEx()`, however using it in the renderer process doesn't create any errors at all.

**Comment by nadavbar** [comment]
Hi @alexrsagen, thanks for reporting these issues.

Are you targeting the Electron code to run as a Dekstop app? Or are you planning to wrap and run it as a windows store app? The problem with the first option is that it seems from the Windows.Devices.SmartCard documentation that this APIs are only supported for windows store apps (at least for windows 8 & 8.1, it doesn't say for windows 10..).
The thing is that WinRT APIs that are supported for desktop apps should have the <a href="https://msdn.microsoft.com/en-us/library/windows/apps/windows.foundation.metadata.dualapipartitionattribute.aspx">Dual API Partition> attribute, and it seems to be missing from the smart card reader APIs.

In case you do want to make it run for desktop, I'll be happy to help and see if we can make this work, but in case that this API is limited for only store apps I'm afraid that there is not much that can be done.

Regarding the constructor errors - from a quick look at the documentation of the SmartCards APIs it seems like you can't directly create a smart card or smart card reader object, but need to request it through a smart card provisioning object. There's a couple of examples for this here: https://code.msdn.microsoft.com/windowsapps/Smart-card-sample-c7d342e0/sourcecode?fileId=86735&pathId=764016036

And Here: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SmartCard/js/js

I'll take a look at the crash you've reported, most definitely seems like a bug.

Regarding the side note - it makes sense you see an error while using it in the browser process since the parameters that are used for the CoInitializeEx call use the MTA flags, while the browser process, which is probably running in a UI thread is probably already using the STA flags.
I'll add more information about this in the documentation though.

**Comment by alexrsagen** [comment]
Thank you very much for the resources and information, i am indeed writing a desktop app. Not planning on releasing it as a store app.

I'd be very happy if we could get this working regardless of it being targeted at store apps.

If we can't, do you know if it's possible to access the Windows PIV/SmartCard API by other means? As a last resort i could write my own binding to some other Windows API.

**Comment by nadavbar** [comment]
In order to verify if we can get it to work - I would try to run a similar code to one of the examples and see if it works.

This modules seems to wrap the windows APIs directly: https://www.npmjs.com/package/smartcardreader

**Comment by alexrsagen** [comment]
I've tried a couple of the examples from [Microsoft/Windows-universal-samples](https://github.com/Microsoft/Windows-universal-samples), though none of them seemed to work, resulting in the same error when trying to create new instances.

`smartcardreader` seems to read the device nicely, but doesn't seem to support encryption/decryption using keys stored on the smartcard, which is what i'm after. Sorry for not clarifying that earlier!

**Comment by nadavbar** [comment]
Can you point me to a specific method in the sample that through that same error? The constructors aren't working is the expected behavior (since you can't create instances yourself), but I'm curious about the other methods.
